// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma-pg/schema.prisma",
  migrations: {
    path: "prisma-pg/migrations",
  },
  datasource: {
    url: process.env["PG_DB_URL"],
  },
});
