// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma-mongo/schema.prisma",
  migrations: {
    path: "prisma-mongo/migrations",
  },
  datasource: {
    url: process.env["MONGO_DB_URL"],
  },
});
